services:
  minio:
    container_name: gng-minio
    image: "minio/minio:latest"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "./minio/data:/data"
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - n8n_network

  redis:
    container_name: gng-redis
    image: redis/redis-stack:latest
    environment:
      REDIS_ARGS: "--save 60 1000 --appendonly yes"
    volumes:
      - "./redis/data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - n8n_network

networks:
  n8n_network:
    external: true 